# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717088eb1bb338fcd66e7b62806e899148dd573422a02b680a5a5cc0096a15fac763a54dbe4840c8247c5c463cdc52a68f7d809fb02dda6c8e41c6515e6f7a82

test:
  secret_key_base: 8223e3ee43d5b5f9d6c15dcaa1c390d11f56884d53db433ab41de931335acfa37c895e270ac9b20d94531ff2be3c520b16e50ea33ff208ee5743c30e83da3015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
